// 에코 — 기억의 지휘자. 공격을 기록하고 재현해 화음을 완성한다.
let echoEffects=[];
const ECHO_NAMES=["파동","균열","잔향"];
function echoDamage(type,replay=false){const lv=player.echoPitchLevel||0,m=[1,1.22,1.48][type];return scaledDamage(player.damage*m*(1+lv*.12)*(replay?(.72+(player.echoAfterimageLevel||0)*.1):1));}
function echoStrike(type,angle,replay=false){
  const range=(185+(player.echoArchiveLevel||0)*12)*(transcended.echoArchive?1.25:1),half=[.42,.62,.82][type],damage=echoDamage(type,replay);let hits=0;
  for(let i=zombies.length-1;i>=0;i--){const z=zombies[i],dx=z.x-player.x,dy=z.y-player.y,d=Math.hypot(dx,dy);if(d>range+z.r||Math.abs(paladinAngleDifference(Math.atan2(dy,dx),angle))>half)continue;z.hp-=damage;hits++;if(type===1){z.x+=Math.cos(angle)*18;z.y+=Math.sin(angle)*18}if(z.hp<=0)killZombie(i,z)}
  echoEffects.push({type:"strike",note:type,x:player.x,y:player.y,a:angle,r:range,life:26,maxLife:26,replay});return hits;
}
function attackWithEcho(){if(player.fireCooldown>0)return;const type=player.echoMemoryType%3,a=Math.atan2(mouse.worldY-player.y,mouse.worldX-player.x);echoStrike(type,a,false);player.echoMemoryType=(type+1)%3;player.fireCooldown=Math.max(14,28-player.fireRateBonus);}
function storeEchoMemory(slot){const type=(player.echoMemoryType+2)%3;player.echoSlots[slot]=type;echoEffects.push({type:"store",note:type,x:player.x,y:player.y,life:34,maxLife:34});if(player.echoSlots.every(v=>v>=0)&&new Set(player.echoSlots).size===3){player.echoHarmonies++;player.echoSlots=[-1,-1,-1];echoEffects.push({type:"harmony",x:player.x,y:player.y,r:230,life:55,maxLife:55});if(player.echoHarmonies>=3)activateEchoSymphony();}}
function replayEchoMemory(){if(player.echoReplayCooldown>0)return;let slot=-1;for(let i=2;i>=0;i--)if(player.echoSlots[i]>=0){slot=i;break}if(slot<0)return;const type=player.echoSlots[slot],a=Math.atan2(mouse.worldY-player.y,mouse.worldX-player.x);echoStrike(type,a,true);if(!transcended.echoAfterimage)player.echoSlots[slot]=-1;player.echoReplayCooldown=Math.max(10,24-(player.echoAfterimageLevel||0)*3);}
function activateEchoSymphony(){player.echoHarmonies=0;const r=430*(transcended.echoArchive?1.25:1),damage=scaledDamage(player.damage*(6+(player.echoPitchLevel||0)*.6));for(let i=zombies.length-1;i>=0;i--){const z=zombies[i];if(Math.hypot(z.x-player.x,z.y-player.y)>r+z.r)continue;z.hp-=damage+(transcended.echoPitch?z.maxHp*.18:0);if(z.hp<=0)killZombie(i,z)}echoEffects.push({type:"symphony",x:player.x,y:player.y,r,life:110,maxLife:110});}
function updateEcho(){if(selectedCharacter!=="echo")return;if(player.echoReplayCooldown>0)player.echoReplayCooldown--;for(let i=echoEffects.length-1;i>=0;i--){const e=echoEffects[i];if(e.type==="symphony"){e.x=player.x;e.y=player.y}if(--e.life<=0)echoEffects.splice(i,1)}}
function drawEchoEffects(){if(selectedCharacter!=="echo")return;worldStart();ctx.save();const now=performance.now();for(const e of echoEffects){const p=1-e.life/e.maxLife,a=Math.max(0,1-p);ctx.save();ctx.globalCompositeOperation="lighter";if(e.type==="strike"){ctx.translate(e.x,e.y);ctx.rotate(e.a);for(let n=0;n<3+e.note;n++){ctx.strokeStyle=`rgba(${e.note===1?168:76},${e.note===2?126:242},255,${a*(.8-n*.1)})`;ctx.lineWidth=e.replay?3:5;ctx.beginPath();ctx.arc(0,0,e.r*(.35+n*.16)*Math.min(1,p*4),-.45-e.note*.18,.45+e.note*.18);ctx.stroke()}}else if(e.type==="store"){const rr=28+p*35;ctx.strokeStyle=`rgba(120,240,255,${a})`;ctx.lineWidth=4;ctx.beginPath();ctx.arc(e.x,e.y,rr,0,Math.PI*2);ctx.stroke();ctx.fillStyle=`rgba(188,140,255,${a})`;ctx.font="bold 18px Arial";ctx.textAlign="center";ctx.fillText(String(e.note+1),e.x,e.y-rr-6)}else {const rr=e.r*Math.min(1,p*2.5),count=e.type==="symphony"?7:3;for(let n=0;n<count;n++){ctx.strokeStyle=`rgba(${n%2?160:72},${n%2?120:245},255,${a*.75})`;ctx.lineWidth=e.type==="symphony"?6:4;ctx.beginPath();ctx.arc(e.x,e.y,rr*(.35+n/count*.65),now*.001*(n%2?1:-1),now*.001*(n%2?1:-1)+Math.PI*1.5);ctx.stroke()}}ctx.restore()}ctx.restore();worldEnd()}
function drawEchoInterface(){if(selectedCharacter!=="echo"||screenMode!=="game")return;const w=Math.min(720,canvas.width-24),h=116,x=(canvas.width-w)/2,y=canvas.height-174;ctx.save();const g=ctx.createLinearGradient(x,y,x+w,y+h);g.addColorStop(0,"rgba(5,15,27,.96)");g.addColorStop(.52,"rgba(16,27,55,.97)");g.addColorStop(1,"rgba(31,15,55,.96)");drawRoundedRect(x,y,w,h,24,g,"#65e8ff",2);ctx.save();ctx.beginPath();ctx.arc(x+55,y+56,40,0,Math.PI*2);ctx.clip();if(echoSpriteLoaded)ctx.drawImage(echoSprite,x+5,y+5,100,100);ctx.restore();ctx.strokeStyle="#84efff";ctx.lineWidth=2;ctx.beginPath();ctx.arc(x+55,y+56,40,0,Math.PI*2);ctx.stroke();ctx.fillStyle="#f2fbff";ctx.font="bold 18px Arial";ctx.fillText("에코",x+105,y+28);ctx.fillStyle="#8cecff";ctx.font="12px Arial";ctx.fillText(`현재 기억: ${ECHO_NAMES[(player.echoMemoryType+2)%3]}  ·  화음 ${player.echoHarmonies}/3`,x+105,y+50);ctx.fillStyle="#aabbd2";ctx.font="11px Arial";ctx.fillText("평타로 기록 · 1/2/3 저장 · 우클릭 재현",x+105,y+70);for(let i=0;i<3;i++){const cx=x+365+i*70,cy=y+48,r=25;ctx.save();ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.clip();ctx.globalAlpha=player.echoSlots[i]>=0?1:.22;if(echoSkillIconAtlas.complete&&echoSkillIconAtlas.naturalWidth){const sw=echoSkillIconAtlas.naturalWidth/2,sh=echoSkillIconAtlas.naturalHeight/2,cell=player.echoSlots[i]>=0?Math.min(2,player.echoSlots[i]):2;ctx.drawImage(echoSkillIconAtlas,(cell%2)*sw,Math.floor(cell/2)*sh,sw,sh,cx-r,cy-r,r*2,r*2)}ctx.restore();ctx.strokeStyle=player.echoSlots[i]>=0?"#75eaff":"#566075";ctx.lineWidth=2;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.stroke();ctx.fillStyle="#b5c9df";ctx.font="bold 10px Arial";ctx.textAlign="center";ctx.fillText(String(i+1),cx,cy+40)}const ux=x+w-55,uy=y+48,ur=28;ctx.save();ctx.beginPath();ctx.arc(ux,uy,ur,0,Math.PI*2);ctx.clip();if(echoSkillIconAtlas.complete&&echoSkillIconAtlas.naturalWidth){const sw=echoSkillIconAtlas.naturalWidth/2,sh=echoSkillIconAtlas.naturalHeight/2;ctx.drawImage(echoSkillIconAtlas,sw,sh,sw,sh,ux-ur,uy-ur,ur*2,ur*2)}ctx.restore();ctx.strokeStyle="#b891ff";ctx.lineWidth=3;ctx.beginPath();ctx.arc(ux,uy,ur,0,Math.PI*2);ctx.stroke();ctx.fillStyle="#fff";ctx.font="bold 12px Arial";ctx.textAlign="center";ctx.fillText(`${player.echoHarmonies}/3`,ux,uy+4);ctx.fillStyle="#e8dcff";ctx.font="10px Arial";ctx.fillText("교향곡",ux,uy+44);ctx.restore()}
