const VARGAS_Q_COOLDOWN=300,VARGAS_E_COOLDOWN=540,VARGAS_X_COOLDOWN=720,VARGAS_R_COOLDOWN=2400;
let vargasEffects=[];
function vargasGrowthMultiplier(){return 1+(player.vargasPredatorLevel||0)*.25+(transcended.vargasPredator?1:0)}
function addVargasMaxHp(amount){if(selectedCharacter!=="vargas")return;let gain=amount*vargasGrowthMultiplier()*(player.vargasUltimateTime>0?2:1);if(transcended.vargasPredator&&amount>=3)gain+=player.maxHp*.01;player.maxHp+=gain;player.vargasGainedHp+=gain;const heal=gain*(1+(player.vargasPulseLevel||0)*.5);player.hp=Math.min(player.maxHp,player.hp+heal);vargasEffects.push({type:"growth",x:player.x,y:player.y-55,value:gain,life:50,maxLife:50})}
function onVargasZombieKilled(z){if(selectedCharacter!=="vargas")return;addVargasMaxHp(z.boss?3:0.6)}
function vargasDamage(mult,hpScale){return scaledDamage((player.damage*mult+player.maxHp*hpScale)*(1+(player.vargasSkeletonLevel||0)*.15))}
function vargasHitCircle(x,y,r,damage,pull=0){let hits=0;for(let i=zombies.length-1;i>=0;i--){const z=zombies[i],dx=x-z.x,dy=y-z.y,d=Math.hypot(dx,dy)||1;if(d>r+z.r)continue;if(pull){z.x+=dx/d*pull;z.y+=dy/d*pull}z.hp-=damage;hits++;if(z.hp<=0)killZombie(i,z)}return hits}
function attackWithVargas(){if(player.fireCooldown>0)return;const a=Math.atan2(mouse.worldY-player.y,mouse.worldX-player.x),range=(player.vargasUltimateTime>0?205:155)*(transcended.vargasSkeleton?1.25:1),arc=1.45;for(let i=zombies.length-1;i>=0;i--){const z=zombies[i],dx=z.x-player.x,dy=z.y-player.y,d=Math.hypot(dx,dy);if(d>range+z.r||Math.abs(paladinAngleDifference(Math.atan2(dy,dx),a))>arc/2)continue;z.hp-=vargasDamage(player.vargasUltimateTime>0?1.65:1.1,.025);z.x+=Math.cos(a)*12;z.y+=Math.sin(a)*12;if(z.hp<=0)killZombie(i,z)}vargasEffects.push({type:"punch",x:player.x,y:player.y,a,r:range,life:22,maxLife:22});player.fireCooldown=Math.max(18,32-player.fireRateBonus)}
function activateVargasQ(){if(player.vargasQCooldown>0)return;const r=(270+(player.vargasSkeletonLevel||0)*18)*(transcended.vargasSkeleton?1.25:1);vargasHitCircle(player.x,player.y,r,vargasDamage(1.8,.04),52);vargasEffects.push({type:"devour",x:player.x,y:player.y,r,life:42,maxLife:42});player.vargasQCooldown=VARGAS_Q_COOLDOWN}
function activateVargasE(){if(player.vargasECooldown>0)return;const cost=Math.min(player.hp-1,player.maxHp*.08);player.hp-=Math.max(0,cost);player.vargasShield+=player.maxHp*(.25+(player.vargasPulseLevel||0)*.04);vargasEffects.push({type:"armor",x:player.x,y:player.y,r:105,life:480,maxLife:480});player.vargasArmorTime=480;player.vargasECooldown=VARGAS_E_COOLDOWN}
function activateVargasX(){if(player.vargasXCooldown>0)return;const dx=mouse.worldX-player.x,dy=mouse.worldY-player.y,len=Math.hypot(dx,dy)||1,d=Math.min(380,len),x=player.x+dx/len*d,y=player.y+dy/len*d,r=(190+(player.vargasSkeletonLevel||0)*16)*(transcended.vargasSkeleton?1.25:1);vargasHitCircle(x,y,r,vargasDamage(2.5,.08));vargasEffects.push({type:"slam",x,y,r,life:48,maxLife:48});player.vargasXCooldown=VARGAS_X_COOLDOWN}
function activateVargasR(){if(player.level<10||player.vargasRCooldown>0)return;player.vargasUltimateTime=480;player.vargasRCooldown=VARGAS_R_COOLDOWN;vargasEffects.push({type:"ultimate",x:player.x,y:player.y,r:260,life:480,maxLife:480})}
function updateVargas(){if(selectedCharacter!=="vargas")return;for(const k of ["vargasQCooldown","vargasECooldown","vargasXCooldown","vargasRCooldown","vargasSecondHeartCooldown"])if(player[k]>0)player[k]--;if(player.vargasArmorTime>0)player.vargasArmorTime--;else player.vargasShield=0;if(player.vargasUltimateTime>0){player.vargasUltimateTime--;player.hp=Math.min(player.maxHp,player.hp+player.maxHp*.025/60)}for(let i=vargasEffects.length-1;i>=0;i--){const e=vargasEffects[i];if(e.type==="armor"||e.type==="ultimate"){e.x=player.x;e.y=player.y}if(--e.life<=0)vargasEffects.splice(i,1)}}
function drawVargasEffects(){if(selectedCharacter!=="vargas")return;worldStart();ctx.save();for(const e of vargasEffects){const p=1-e.life/e.maxLife,a=Math.max(0,1-p);ctx.save();ctx.globalCompositeOperation="lighter";if(e.type==="punch"){ctx.translate(e.x,e.y);ctx.rotate(e.a);ctx.fillStyle=`rgba(86,255,146,${a*.28})`;ctx.strokeStyle=`rgba(160,255,195,${a})`;ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(25,-35);ctx.lineTo(e.r,0);ctx.lineTo(25,35);ctx.closePath();ctx.fill();ctx.stroke()}else if(e.type==="devour"){ctx.strokeStyle=`rgba(72,255,135,${a})`;ctx.lineWidth=9;for(let n=0;n<3;n++){ctx.beginPath();ctx.arc(e.x,e.y,e.r*(1-p*.75)-n*18,p*5+n,p*5+n+Math.PI*1.35);ctx.stroke()}}else if(e.type==="armor"){ctx.strokeStyle=`rgba(96,255,151,${Math.min(.75,e.life/35)})`;ctx.lineWidth=6;ctx.beginPath();for(let n=0;n<6;n++){const q=n*Math.PI/3-Math.PI/2,x=e.x+Math.cos(q)*e.r,y=e.y+Math.sin(q)*e.r;n?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.stroke()}else if(e.type==="slam"){const rr=e.r*Math.min(1,p*2);ctx.strokeStyle=`rgba(110,255,160,${a})`;ctx.lineWidth=14;ctx.beginPath();ctx.arc(e.x,e.y,rr,0,Math.PI*2);ctx.stroke();for(let n=0;n<12;n++){const q=n*Math.PI/6;ctx.beginPath();ctx.moveTo(e.x+Math.cos(q)*rr*.25,e.y+Math.sin(q)*rr*.25);ctx.lineTo(e.x+Math.cos(q)*rr,e.y+Math.sin(q)*rr);ctx.stroke()}}else if(e.type==="ultimate"){const pulse=1+Math.sin(performance.now()*.006)*.04,g=ctx.createRadialGradient(e.x,e.y,35,e.x,e.y,e.r*pulse);g.addColorStop(0,"rgba(30,125,70,.2)");g.addColorStop(.75,"rgba(38,255,116,.08)");g.addColorStop(1,"rgba(38,255,116,0)");ctx.fillStyle=g;ctx.beginPath();ctx.arc(e.x,e.y,e.r*pulse,0,Math.PI*2);ctx.fill();ctx.strokeStyle="rgba(104,255,156,.55)";ctx.lineWidth=5;ctx.beginPath();ctx.arc(e.x,e.y,e.r*.75*pulse,0,Math.PI*2);ctx.stroke()}ctx.restore();if(e.type==="growth"){ctx.fillStyle=`rgba(128,255,172,${a})`;ctx.font="bold 16px Arial";ctx.textAlign="center";ctx.fillText(`최대 체력 +${e.value.toFixed(1)}`,e.x,e.y-p*35)}}ctx.restore();worldEnd()}
